version: "3.7"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public/:/var/www/html/
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=hello
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
networks:
  frontend:
  backend:
